[patch."https://github.com/sigmatactical-org/sigma-theme.git"]
sigma-theme = { path = "../theme" }

[patch."https://github.com/sigmatactical-org/sigma-pg.git"]
sigma-pg = { path = "../sigma-pg" }

[patch."https://github.com/sigmatactical-org/identity.git"]
sigma-identity-nav = { path = "../identity/nav" }

[patch."https://github.com/sigmatactical-org/cart.git"]
sigma-cart-nav = { path = "../cart/nav" }

[patch."https://github.com/sigmatactical-org/contact.git"]
sigma-contact-nav = { path = "../contact/nav" }
